### ISSUE TITLE
`-h` or `--help` flag output differs from normal `gozer` help output 

### ISSUE THREAD

**Issue by cooperqmarshall** [dannyvankooten/gozer#1]
Hi, when running `gozer -h` or `gozer --help` I get:
```
Usage of ./gozer:
  -c string
    	(default "config.toml")
  -config string
    	(default "config.toml")
  -r string
    	
  -root string
```
Which seems to be an automatically generated help text. When I run `gozer` (no arguments) I get a more useful help text:
```
Gozer - a fast & simple static site generator

Usage: gozer [OPTIONS] <COMMAND>

Commands:
	build	Deletes the output directory if there is one and builds the site
	serve	Builds the site and starts an HTTP server on http://localhost:8080
	new     Creates a new site structure in the given directory

Options:
	-r, --root <ROOT> Directory to use as root of project (default: .)
	-c, --config <CONFIG> Path to configuration file (default: config.toml)
```

go version: `go1.21.4 linux/amd64`

Are you accepting contributions? If so, I would be happy to take a stab at implementing this if its something you would like added. 

P.S. I saw your reddit post about this project and thought it looked cool! I'm working on setting up my blog using gozer and have enjoyed it so far <3

**Comment by dannyvankooten** [comment]
Hey, so cool that you’re trying Gozer! Never knew Go provided a default help text when using their flag parsing utilities (or at least that’s my hunch of what’s going on), definitely open for contributions.Op 14 feb. 2024 om 04:33 heeft Cooper Marshall ***@***.***> het volgende geschreven:﻿
Hi, when running gozer -h or gozer --help I get:
Usage of ./gozer:
  -c string
    	(default "config.toml")
  -config string
    	(default "config.toml")
  -r string
    	
  -root string

Which seems to be an automatically generated help text. When I run gozer (no arguments) I get a more useful help text:
Gozer - a fast & simple static site generator

Usage: gozer [OPTIONS] <COMMAND>

Commands:
	build	Deletes the output directory if there is one and builds the site
	serve	Builds the site and starts an HTTP server on http://localhost:8080
	new     Creates a new site structure in the given directory

Options:
	-r, --root <ROOT> Directory to use as root of project (default: .)
	-c, --config <CONFIG> Path to configuration file (default: config.toml)

go version: go1.21.4 linux/amd64
Are you accepting contributions? If so, I would be happy to take a stab at implementing this if its something you would like added.
P.S. I saw your reddit post about this project and thought it looked cool! I'm working on setting up my blog using gozer and have enjoyed it so far <3

**Comment by cooperqmarshall** [comment]
Yeah seems like `-h` and `--help` [get default messages](https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/flag/flag.go;l=1111) which a pretty cool but sorta annoying feature.
