### ISSUE TITLE
panic in `copyFile()` after removing `public/`

### ISSUE THREAD

**Issue by cooperqmarshall** [dannyvankooten/gozer#4]
Hi Danny,

I found that `gozer build` panics after removing the `public/` directory
```
$ gozer build
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8402fe]

goroutine 1 [running]:
main.copyFile({0x8f3c44, 0x6}, {0x0, 0x0}, {0x8f28f1, 0x5})
        /home/user/code/gozer/fs.go:48 +0x5e
main.buildSite.copyDirRecursively.func2({0x8f3c44, 0x6}, {0x0, 0x0}, {0x4fa025?, 0x8f3c44?})
        /home/user/code/gozer/fs.go:79 +0x7d
path/filepath.WalkDir({0x8f3c44, 0x6}, 0xc00033fcb8)
        /home/user/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.4.linux-amd64/src/path/filepath/path.go:530 +0x4a
main.copyDirRecursively(...)
        /home/user/code/gozer/fs.go:77
main.buildSite({0x0, 0x0}, {0x8f8fa6, 0xb})
        /home/user/code/gozer/gozer.go:508 +0x829
main.main()
        /home/user/code/gozer/gozer.go:415 +0x3d2
```

Steps to reproduce:
```
$ gozer new   # Create new gozer project
$ rm -r public/   # Remove `public/`
$ gozer build   # panics
```

This seems to be related to the `WalkDirFunc` callback in `filepath.WalkDir()`. The [docs](https://pkg.go.dev/io/fs#WalkDirFunc) describe how the `err` argument in `WalkDirFunc` can be non-nil in some cases.

I stumbled upon this after accidentally removing my `public` directory so definitely user error on this one haha! Happy to post a PR with a fix to log the error instead of panicking if that would be alright.

**Comment by dannyvankooten** [comment]
Hey @cooperqmarshall, 

Nice catch! 

> I stumbled upon this after accidentally removing my public directory so definitely user error on this one haha! Happy to post a PR with a fix to log the error instead of panicking if that would be alright.

Sure thing. An error message would be way nicer than what the panic currently gives us. I can take a look some time myself, but if you're up for it then that'd be awesome. :+1:
